config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    resources :recipes
  end
  resources :recipes
  get "/login" => 'sessions#new'
  post "/login" => 'sessions#create'
  get "/logout" => 'sessions#destroy'
  root "sessions#index"
  get '/users/auth/facebook/callback' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  
    
  resources :categories
  resources :ingredients
  resources :comments
  resources :ratings
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
    has_many :recipe_categories
    has_many :categories, through: :recipe_categories
    has_many :comments
    has_many :ratings
    validates :title, presence: true
    validates :level, inclusion: {in: %w(Easy Intermediate Advanced), message: "Please be sure to enter Easy, Intermediate or Advanced"}
    validates :cook_time, presence: true
    validates :serving_size, numericality: {only_integer: true}
    validates :ingredients_list, presence: true
    validates :directions, presence: true
    validates :categories, presence: true
    validates :ingredients, presence: true
    accepts_nested_attributes_for :categories
    accepts_nested_attributes_for :ingredients
    #scope :by_new, -> { order(created_at: :desc) }

    def self.by_user(user_id)
        where(user: user_id)
    end

    def self.by_new
        order(created_at: :desc)
    end

    def self.by_old
        order(created_at: :asc)
    end

    def categories_attributes=(category_attributes)
        category_attributes.values.each do |category_attribute|
            if category_attribute['name'].present?
                category = Category.find_or_create_by(category_attribute)
                self.categories << category
            end
        end
    end

    def ingredients_attributes=(ingredient_attributes)
        ingredient_attributes.values.each do |ingredient_attribute|
            if ingredient_attribute["name"].present?
                ingredient = Ingredient.find_or_create_by(ingredient_attribute)
                self.ingredients << ingredient
            end
        end
    end

    def average_rating
        self.ratings.average(:score)
    end
        
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    layout "logged_in"
    before_action :require_login

    def index
        @users = User.all
        if !params[:user].blank?
            @recipes = Recipe.by_user(params[:user])
        elsif !params[:date].blank?
            if params[:date] == "Descending"
                @recipes = Recipe.by_new
            else
                @recipes = Recipe.by_old
            end
        else
            if params[:user_id]
                @user = User.find_by(id: params[:user_id])
                if @user.nil?
                    redirect_to users_path, alert: "User not found."
                else
                    @recipes = @user.recipes
                end
            else
                @recipes = Recipe.all
            end
        end
    end

    def new
        if params[:user_id] && !User.exists?(params[:user_id])
            redirect_to users_path, alert: "User not found."
        else
            @recipe = Recipe.new(user_id: params[:user_id])
        end
    end

    def create
        @recipe = current_user.recipes.build(recipes_params)
        if @recipe.save
            redirect_to @recipe
        else
            render :new
        end
    end

    def show
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @recipe = @user.recipes.find_by(id: params[:id])
            if @recipe.nil?
                redirect_to user_recipes_path(@user), alert: "Recipe not found."
            end
        else
            @recipe = Recipe.find(params[:id])
        end
    end

    def edit
        if params[:user_id]
            user = User.find_by(id: params[:user_id])
            if user.nil?
                redirect_to users_path, alert: "User not found."
            else
                @recipe = user.recipes.find_by(id: params[:id])
                redirect_to user_recipes_path(user), alert: "Recipe not found." if @recipe.nil? 
            end
        else
            @recipe = Recipe.find(params[:id])
        end
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.user == current_user
            if @recipe.update(recipes_params)
                redirect_to recipe_path(@recipe)
            else
                render :edit
            end
        else
            redirect_to recipes_path, alert: "You are unable to edit other user's recipes!!!"
        end
    end

    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to recipes_path
    end


    private
    def recipes_params
        params.require(:recipe).permit(:user_id, :title, :level, :cook_time, :serving_size, :directions, :ingredients_list, category_ids: [], ingredient_ids: [], categories_attributes: [:name], ingredients_attributes: [:name])
    end

end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
    <%= render partial: "users/error", locals: {error_term: @recipe} %>
    <%= f.label "Title of Recipe" %><br>
    <%= f.text_field :title %><br>
    <%= f.label "Level of Difficulty (Easy, Intermediate or Advanced)" %><br>
    <%= f.text_field :level %><br>
    <%= f.label "Cook Time (Please include minutes and/or hour required)" %><br>
    <%= f.text_field :cook_time %><br>
    <%= f.label "Serving Size (Please enter the number of servings)" %><br>
    <%= f.text_field :serving_size %><br>
    <%= f.label "Ingredients List(Please list out all ingredients including the quantity)" %><br>
    <%= f.text_area :ingredients_list %><br>
    <%= f.label "Directions (Please list out the directions in a numbered list)" %><br>
    <%= f.text_area :directions %><br>
    <%= f.label "Categories (Please select the applicable categories or add a new category by typing the category in the field)" %><br>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %><br>
    <%= f.fields_for :categories, @recipe.categories.build do |categories_field| %>
        <%= categories_field.label "Add a Unique Category:" %><br>
        <%= categories_field.text_field :name %><br>
    <% end %>
    <%= f.label "Ingredients Selection(Please select the applicable ingredients or add a new ingredient by typing the ingredient in the field)" %><br>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %><br><br>
    <%= f.fields_for :ingredients, @recipe.ingredients.build do |ingredients_field| %>
        <%= ingredients_field.label "Add a Unique Ingredient:" %><br>
        <%= ingredients_field.text_field :name %><br>
    <% end %>
    <%= f.submit "Submit Recipe" %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render "form" %>

app/views/recipes/index.html.erb
<h1>All Recipes Posted by Our Users</h1>
<%= flash[:alert] %>
<ul>
<% @recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe_path(recipe) %></li>
<% end %>
</ul>

<div>
    <h3>Filter Recipes By User:</h3>
    <%= form_tag("/recipes", method: 'get') do %>
        <%= select_tag "user", options_from_collection_for_select(@users, "id", "name"), include_blank: true %>
        
    
    <h3>Order By Creation Date:</h3>
    <%= select_tag "date", options_for_select(['Ascending', "Descending"]), include_blank: true %>

    <%= submit_tag "Filter" %>
    <% end %>
</div>

app/views/recipes/new.html.erb
<h1>Add a Recipe</h1>
<%= render "form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<div class= "title-container">
<h2>Created By: <%= @recipe.user.name %></h2>
</div>

<table class="center">
<thead>
    <tr>
        <th>Level of Difficulty</th>
        <th>Cook Time</th>
        <th>Serving Size</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td><%= @recipe.level %></td>
        <td><%= @recipe.cook_time %></td>
        <td><%= @recipe.serving_size %></td>
    </tr>
</tbody>
</table>

<div class= "title-container">
<h3>Average Rating: <%= @recipe.average_rating %></h3>
</div>

<div class= "title-container">
<%= link_to "Edit Recipe", edit_recipe_path(@recipe) if @recipe.user == current_user %><br>
<%= link_to "Delete Recipe", @recipe, method: :delete, data: {confirm: "Are you sure you want to delete this recipe?"} if @recipe.user == current_user %>
</div>

<div class="test_row">
<div class="test_column">
<h3>Ingredients:</h3>
<%= @recipe.ingredients_list %>
</div>
<div class="test_column">
<h3>Directions:</h3>
<%= @recipe.directions %><br><br>
</div>
</div>

<div class="test_row">
<div class="test_column">
<h3>Categories:</h3>
<ul>
<% @recipe.categories.uniq.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
<% end %>
</ul>
</div>
<div class="test_column">
<h3>Links to Other Recipes With Similar Ingredients</h3>
<ul>
<% @recipe.ingredients.uniq.each do |ingredient| %>
    <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
<% end %>
</ul>
</div>
</div>

<div class="test_row">
<div class="test_column">
<h3>Ratings:</h3>
<ul>
<% @recipe.ratings.each do |rating| %>
    <li><%= rating.score %>/10 - <%= rating.user.name %></li>
<% end %>
</ul>
</div>
<div class="test_column">
<h3>Add Rating Out of 10</h3>
<%= form_for @recipe.ratings.build do |f| %>
    <%= f.hidden_field :recipe_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.text_field :score %><br>
    <%= f.submit "Submit Rating" %>
<% end %>
</div>
</div>

<div class="test_row">
<div class="test_column">
<h3>Comments:</h3>
<ul>
<% @recipe.comments.each do |comment| %>
    <li><%= comment.user.name %> says: <%= comment.content %></li>
<% end %>
</ul>
</div>
<div class="test_column">
<h3>Add Comment</h3>
<%= form_for @recipe.comments.build do |f| %>
    <%= f.hidden_field :recipe_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label "Please type in your comments regarding this recipe" %><br>
    <%= f.text_area :content %><br>
    <%= f.submit "Submit Comment" %>
<% end %>
</div>
</div>

<br>