config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    resources :recipes
  end
  resources :recipes
  get "/login" => 'sessions#new'
  post "/login" => 'sessions#create'
  get "/logout" => 'sessions#destroy'
  root "sessions#index"
  get '/users/auth/facebook/callback' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  
    
  resources :categories
  resources :ingredients
  resources :comments
  resources :ratings
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
    has_many :comments
    has_many :ratings
    has_secure_password
    validates :name, presence: true
    validates :email, uniqueness: true
    validates :email, presence: true
    validates :password, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:show]
    
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(users_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :layout => "logged_in"
    end
        
    private
    def users_params
        params.require(:user).permit(:name, :email, :password)
    end

end

app/views/users/_error.html.erb
<% if error_term.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(error_term.errors.count, "error")%> prohibited this form from being saved:</h2>
            <ul>
            <% error_term.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
<% end %>

app/views/users/index.html.erb
<h1>List of Users</h1>
<%= flash[:alert] %>
<ul>
<% @users.each do |user| %>
    <li><%= link_to user.name, user_recipes_path(user) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Create A New Account</h1>
<%= form_for(@user) do |f| %>
    <%= render partial: "error", locals: {error_term: @user} %>
    <%= f.label "Name:" %><br>
    <%= f.text_field :name %><br>
    <%= f.label "Email:" %><br>
    <%= f.text_field :email %><br>
    <%= f.label "Password:" %><br>
    <%= f.password_field :password %><br><br>
    <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome Back <%= @user.name %>!</h1>
<div class="title-container">
<h2>What would you like to do today?</h2>
</div>
<h3>Your Recipes</h3>
<ul>
<% @user.recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe_path(recipe) %></li>
<% end %>
</ul>