config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    resources :recipes
  end
  resources :recipes
  get "/login" => 'sessions#new'
  post "/login" => 'sessions#create'
  get "/logout" => 'sessions#destroy'
  root "sessions#index"
  get '/users/auth/facebook/callback' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  
    
  resources :categories
  resources :ingredients
  resources :comments
  resources :ratings
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :recipe_categories
    has_many :recipes, through: :recipe_categories
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    layout "logged_in"
    before_action :require_login

    def new
        @category = Category.new
    end

    def index
        @categories = Category.all 
    end

    def create
        @category = Category.new(categories_params)
        if @category.save
            redirect_to categories_path
        else
            render :new
        end
    end

    def show
        @category = Category.find(params[:id])
    end

    private
    def categories_params
        params.require(:category).permit(:name)
    end
end

app/views/categories/index.html.erb
<h1>List of All Categories</h1>
<ul>
<% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
<% end %>
</ul>

app/views/categories/new.html.erb
<h1>Add Category</h1>
<%= form_for @category do |f| %>
    <%= render partial: "users/error", locals: {error_term: @category} %>
    <%= f.label "Name of Category:" %><br>
    <%= f.text_field :name %><br><br>
    <%= f.submit "Submit Category" %>
<% end %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>
<ul>
<% @category.recipes.uniq.each do |recipe| %>
    <li><%= link_to recipe.title, recipe_path(recipe) %></li>
<% end %>
</ul>