config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index] do
    resources :recipes
  end
  resources :recipes
  get "/login" => 'sessions#new'
  post "/login" => 'sessions#create'
  get "/logout" => 'sessions#destroy'
  root "sessions#index"
  get '/users/auth/facebook/callback' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  
    
  resources :categories
  resources :ingredients
  resources :comments
  resources :ratings
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cayenne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="style.css">
  </head>

  <body>
  <header>
           <img src="https://cdn.shopify.com/s/files/1/1068/6100/products/cayennepepper_1024x1024.jpg?v=1448195713">
            <nav>
                <ul>
                    <li><%= link_to "Welcome", root_path %></li>
                    <li><%= link_to "Create An Account", new_user_path %></li>
                    <li><%= link_to "Sign In Using Email", login_path %></li>
                    <li><%= link_to "Sign In Using Facebook", '/auth/facebook' %></li>
                    <li><%= link_to "Logout", logout_path %></li>
                </ul>
            </nav>
        </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/logged_in.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cayenne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="style.css">
  </head>

  <body>
  <header>
           <img src="https://cdn.shopify.com/s/files/1/1068/6100/products/cayennepepper_1024x1024.jpg?v=1448195713">
            <nav>
                <ul>
                    <li><%= link_to "Home", user_path(current_user) %></li>
                    <li><%= link_to "See All Recipes", recipes_path %></li>
                    <li><%= link_to "Add New Recipes", new_recipe_path %></li>
                    <li><%= link_to "Add New Ingredients Manually", new_ingredient_path %></li>
                    <li><%= link_to "Add New Categories Manually", new_category_path %></li>
                    <li><%=link_to "Logout", logout_path %></li>
                </ul>
            </nav>
        </header>
    <%= yield %>
  </body>
</html>